// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Banco.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240426122444_Cavalo")]
    partial class Cavalo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoCardapio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoCardapio");

                    b.HasKey("Id");

                    b.ToTable("Cardapio", (string)null);
                });

            modelBuilder.Entity("Dominio.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeDoCliente");

                    b.HasKey("Id");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Dominio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeProduto");

                    b.Property<double>("Preco")
                        .HasColumnType("float")
                        .HasColumnName("PrecoProduto");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Dominio.ProdutoCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardapioID")
                        .HasColumnType("int")
                        .HasColumnName("IDCardapio");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int")
                        .HasColumnName("IDProduto");

                    b.HasKey("Id");

                    b.HasIndex("CardapioID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ProdutosCardapio", (string)null);
                });

            modelBuilder.Entity("Dominio.ProdutoComanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaID")
                        .HasColumnType("int")
                        .HasColumnName("IDComanda");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int")
                        .HasColumnName("IDProduto");

                    b.HasKey("Id");

                    b.HasIndex("ComandaID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("ProdutosComanda", (string)null);
                });

            modelBuilder.Entity("Dominio.ProdutoCardapio", b =>
                {
                    b.HasOne("Dominio.Cardapio", "Cardapio")
                        .WithMany("Produtos")
                        .HasForeignKey("CardapioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Produto", "Produto")
                        .WithMany("ProdutoCardapios")
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Dominio.ProdutoComanda", b =>
                {
                    b.HasOne("Dominio.Comanda", "Comanda")
                        .WithMany("Produtos")
                        .HasForeignKey("ComandaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Produto", "Produto")
                        .WithMany("ProdutoComandas")
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Dominio.Cardapio", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Dominio.Comanda", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Dominio.Produto", b =>
                {
                    b.Navigation("ProdutoCardapios");

                    b.Navigation("ProdutoComandas");
                });
#pragma warning restore 612, 618
        }
    }
}
